name: CI

on:
  pull_request:
  push:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # check:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v1
  #   - name: Setup Rust toolchain
  #     run: rustup default stable
  #   - name: Build
  #     run: cargo build --locked --verbose
  #   # - name: Run tests
  #   #  run: cargo test --locked --verbose
  #   - name: Rustfmt and Clippy
  #     run: |
  #       cargo fmt -- --check
  #       cargo clippy
  test:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: Setup Rust toolchain
      run: rustup default stable
    - uses: ok-nick/setup-aftman@v0.4.2
    - name: Install aftman tools
      run: aftman install
    - name: Build run-in-roblox plugin
      run: cd plugin && lune build.lua
    - name: Build test place
      run: cd demo && rojo build default.project.json -o test.rbxl
    - name: Build
      run: cargo build --locked
    - name: Run example script
      run: cargo run -- run --place-file ./demo/test.rbxl --script ./demo/hello.lua --universe-id 28220420 --place-id 95206881 --creator-id 5137677267 --creator-type 0 --oneshot
